Cmake fix
jrl-umi3218/mc_rbdyn_urdf pull request #8
Opened 2018-03-23 19:38 UTC by ahundt

Identical to https://github.com/jrl-umi3218/mc_rbdyn_urdf/pull/7 but also actually updates the cmake subrepository so it should be ready to merge now.

2018-03-23 19:40 UTC, ahundt commented
@gergondet any chance you could give this a quick look?

2018-03-26 02:28 UTC, gergondet requested changes
Thanks for the PR.

Will merge when these 2 minor issues are addressed.

2018-03-26 02:28 UTC, gergondet commented on CMakeLists.txt
> +SET(CXX_DISABLE_WERROR True)
Please use lower-case `set` here

2018-03-26 02:28 UTC, gergondet commented on CMakeLists.txt
> +SETUP_PROJECT_PACKAGE_FINALIZE()
Please use lower-case `setup_project_package_finalize()` here

2018-03-26 02:29 UTC, gergondet commented
Hi @ahundt, thanks to you and @Chunting for this PR.

I will merge once these two small issues are fixed.

Does this mean we can close #7?

2018-03-28 22:59 UTC, ahundt commented
@gergondet should be fixed and yes #7 can be closed

2018-03-29 00:58 UTC, gergondet approved these changes

2018-03-29 00:58 UTC, gergondet commented
Thanks!

Merging this and closing #7

2018-03-29 00:59 UTC, merged